apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: selenium
  name: selenium-grid
  labels:
    app: selenium-grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-grid
  template:
    metadata:
      labels:
        app: selenium-grid
    spec:
      volumes:
      - name: dshm
        emptyDir: {}
      containers:
        - name: sel-grid
          image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210823
          ports:
            - containerPort: 4444
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: selenium
  name: selenium-video
  labels:
    app: selenium-video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-video
  template:
    metadata:
      labels:
        app: selenium-video
    spec:
      containers:
        - name: sel-grid
          image: selenium/video:ffmpeg-4.3.1-20210823
---
apiVersion: v1
kind: Service
metadata:
  namespace: selenium
  name: selenium-grid
spec:
  selector:
    app: selenium-grid
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "selenium"
  name: "selenium-ingress"
spec:
  rules:
  - host: "selenium.192.168.1.150.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
            service: 
                name: "selenium-grid"
                port:
                   number: 4444
            