apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: {{ .Values.mySqlImage }}
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_USER
          value: keycloak
        - name: MYSQL_DATABASE
          value: keycloak
        ports:
        - containerPort: 3306
          name: mysql
        # livenessProbe:
        #   exec:
        #     command: ["mysqladmin", "ping"]
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        # readinessProbe:
        #   exec:
        #     # Check we can execute queries over TCP (skip-networking is off).
        #     command: ["mysqladmin", "ping"]
        #   initialDelaySeconds: 5
        #   periodSeconds: 2
        #   timeoutSeconds: 1
{{- if eq .Values.persistence.enabled true }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "local"
    spec:
      volumeName: "keycloak-next-mysql-{{ .Values.env }}"
      storageClassName: "local"
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "keycloak-next-mysql-{{ .Values.env }}"
  labels:
    type: "local"
spec:
  storageClassName: "local"
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/{{ .Values.rootVolumeFolder }}/{{ .Release.Name }}-{{ .Values.env }}/keycloak-next-mysql-{{ .Values.env }}"
{{ end }}