apiVersion: apps/v1
kind: Deployment
metadata:
  name: movietalk-ui
  labels:
    app: movietalk-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movietalk-ui
  template:
    metadata:
      labels:
        app: movietalk-ui
    spec:
      containers:
        - name: movietalk-ui-next
          image: modeseven/movietalk-ui-next:{{ .Values.uiImageTag }}
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          # readinessProbe:
          #   httpGet:
          #     path: /addwizard
          #     port: 80
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 5
          #   periodSeconds: 8
          #   failureThreshold: 2
          # livenessProbe:
          #   httpGet:
          #     path: /addwizard
          #     port: 80
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 5
          #   periodSeconds: 8
          #   failureThreshold: 2
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/.env.local
              name: env-local
              subPath: .env.local
          # env:
          # - name: KEYCLOAK_HOST
          #   value: {{ .Values.tlsEnabled | ternary "https" "http" }}://{{ .Values.hostName }}
          # - name: REACT_APP_OMDB_API_KEY
          #   value: {{ .Values.ombikey }}
          # - name: ENV
          #   value: {{ .Values.env }}     
          # - name: VERSION
          #   value: {{ .Values.uiImageTag }}
          # - name: API_VERSION
          #   value: {{ .Values.apiImageTag }}
      volumes:
      - configMap:
          items:
          - key: .env
            path: .env.local
          name: env-local
        name: env-local                    
---
apiVersion: v1
kind: Service
metadata:
  name: movietalk-ui
spec:
  selector:
    app: movietalk-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: env-local
data:
  .env: |
    NEXT_PUBLIC_KEYCLOAK_HOST=http://temp.192.168.1.150.nip.io
    NEXT_PUBLIC_REACT_APP_OMDB_API_KEY=dc1a9808
    NEXT_PUBLIC_UI_VERSION=1.1.5
    NEXT_PUBLIC_API_VERSION=1.0.0
    NEXT_PUBLIC_ENV=temp