apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: esis-e2e
  namespace: argocd
spec:
  destination:
    namespace: esis-e2e
    server: 'https://kubernetes.default.svc'
  info:
    - name: test
      value: test
  project: demo
  source:
    helm:
      valueFiles:
        - values.e2e.yml
    path: charts/esis
    repoURL: 'git@github.com:modeseven/esis-infra.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true