apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movietalk-perf
  namespace: argocd
spec:
  destination:
    namespace: movietalk-perf
    server: 'https://kubernetes.default.svc'
  info:
    - name: test
      value: test
  project: demo
  source:
    helm:
      valueFiles:
        - values.perf.yml
    path: charts/movietalk
    repoURL: 'git@github.com:modeseven/demoinfra.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true